name: deploy

on:
  push:
    branches: 
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd endless-galaxy-server && yarn install
      - run: cd endless-galaxy-server && yarn build
      - run: rsync -av endless-galaxy-server/build/ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:app
      - run: ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} -e "cd app && yarn install --production && node ace migration:run --force && pm2 reload endless-galaxy"
